"""
Add is_ministry field into the user profile model
--------------------------------------------------
Revision ID: aa0e78da02e6
Revises: 35a4821cae9c
Create Date: 2025-08-26 23:09:14.962367
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aa0e78da02e6'
down_revision: Union[str, None] = '35a4821cae9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_user_profile', sa.Column('is_ministry', sa.Boolean(), server_default=sa.text("false"), nullable=False, comment='Is ministry'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_user_profile', 'is_ministry')
    # ### end Alembic commands ###
