"""
Add type field for Resource model
--------------------------------------------------
Revision ID: d8fa635e06eb
Revises: 80234a5bc35f
Create Date: 2025-09-09 16:10:36.427035
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd8fa635e06eb'
down_revision: Union[str, None] = '80234a5bc35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_resource', sa.Column('type', sa.Integer(), nullable=False, comment='Resource type, Enum: ResourceType'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_resource', 'type')
    # ### end Alembic commands ###
