"""
Create password reset token table
--------------------------------------------------
Revision ID: b85513545130
Revises: 5e0db16a3a0e
Create Date: 2025-11-17 17:10:06.709244
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b85513545130'
down_revision: Union[str, None] = '5e0db16a3a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_password_reset_token',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Reset token'),
    sa.Column('token_hash', sa.String(length=512), nullable=False, comment='Hashed token for verification'),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False, comment='Token expiration time'),
    sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Token used time'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP address when token was created'),
    sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent when token was created'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_password_reset_token_user_id_portal_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_password_reset_token')),
    schema='public'
    )
    op.create_index(op.f('ix_portal_password_reset_token_expires_at'), 'portal_password_reset_token', ['expires_at'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_password_reset_token_token'), 'portal_password_reset_token', ['token'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_password_reset_token_user_id'), 'portal_password_reset_token', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_password_reset_token_user_id'), table_name='portal_password_reset_token', schema='public')
    op.drop_index(op.f('ix_portal_password_reset_token_token'), table_name='portal_password_reset_token', schema='public')
    op.drop_index(op.f('ix_portal_password_reset_token_expires_at'), table_name='portal_password_reset_token', schema='public')
    op.drop_table('portal_password_reset_token', schema='public')
    # ### end Alembic commands ###
