"""
Create rbac-related tables
--------------------------------------------------
Revision ID: 4372a1805460
Revises: 2e86f0460cfb
Create Date: 2025-08-22 02:18:58.656368
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4372a1805460'
down_revision: Union[str, None] = '2e86f0460cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portal_resource',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('code', sa.String(length=32), nullable=False, comment='Resource code (e.g., user, course, article)'),
        sa.Column('name', sa.String(length=64), nullable=True, comment='Resource name'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is resource active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_resource')),
        sa.UniqueConstraint('code', name=op.f('uq_portal_resource_code')),
        schema='public'
    )
    op.create_table(
        'portal_role',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('code', sa.String(length=32), nullable=False, comment='Role code'),
        sa.Column('name', sa.String(length=64), nullable=True, comment='Role name'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is role active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_role')),
        sa.UniqueConstraint('code', name=op.f('uq_portal_role_code')),
        schema='public'
    )
    op.create_table(
        'portal_third_party_provider',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=16), nullable=False, comment='Provider name, Enum: Provider'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_third_party_provider')),
        sa.UniqueConstraint('name', name=op.f('uq_portal_third_party_provider_name')),
        schema='public'
    )
    op.create_table(
        'portal_user',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('phone_number', sa.String(length=16), nullable=False, comment='Phone number, unique identifier'),
        sa.Column('email', sa.String(length=64), nullable=True, comment='Email, unique identifier'),
        sa.Column('password_hash', sa.String(length=512), nullable=True, comment='Password hash'),
        sa.Column('salt', sa.String(length=128), nullable=True, comment='Salt for password hash'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is active'),
        sa.Column('verified', sa.Boolean(), nullable=True, comment='Is verified'),
        sa.Column('last_login_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Last login'),
        sa.Column('password_changed_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password last changed time'),
        sa.Column('password_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Password expiration time'),
        sa.Column('is_superuser', sa.Boolean(), nullable=True, comment='Is superuser'),
        sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Is admin'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_user')),
        sa.UniqueConstraint('email', name=op.f('uq_portal_user_email')),
        sa.UniqueConstraint('phone_number', name=op.f('uq_portal_user_phone_number')),
        schema='public'
    )
    op.create_table(
        'portal_verb',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('action', sa.String(length=32), nullable=False, comment='Verb action (e.g., create, read, update, delete)'),
        sa.Column('display_name', sa.String(length=64), nullable=True, comment='Display name'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is verb active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_verb')),
        sa.UniqueConstraint('action', name=op.f('uq_portal_verb_action')),
        schema='public'
    )
    op.create_table(
        'portal_permission',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
        sa.Column('verb_id', sa.UUID(), nullable=False, comment='Verb ID'),
        sa.Column('code', sa.String(length=128), nullable=False, comment='Permission Code (e.g., user:read)'),
        sa.Column('display_name', sa.String(length=128), nullable=True, comment='Display name'),
        sa.Column('expire_date', sa.DateTime(timezone=True), nullable=True, comment='Expiration time, can be used for temporary authorization'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is permission active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['resource_id'],
            ['public.portal_resource.id'],
            name=op.f('fk_portal_permission_resource_id_portal_resource'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['verb_id'], ['public.portal_verb.id'], name=op.f('fk_portal_permission_verb_id_portal_verb'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_permission')),
        sa.UniqueConstraint('resource_id', 'verb_id', name=op.f('uq_portal_permission_resource_id_verb_id')),
        schema='public'
    )
    op.create_table(
        'portal_user_profile',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('display_name', sa.String(length=64), nullable=True, comment='Display name'),
        sa.Column('gender', sa.Integer(), nullable=True, comment='Refer to Gender enum'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_user_profile_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_user_profile')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_user_profile_user_id'), 'portal_user_profile', ['user_id'], unique=True, schema='public')
    op.create_table(
        'portal_user_role',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['public.portal_role.id'], name=op.f('fk_portal_user_role_role_id_portal_role'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_user_role_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_portal_user_role')),
        schema='public'
    )
    op.create_table(
        'portal_user_third_party_auth',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('provider_id', sa.UUID(), nullable=False, comment='Provider ID'),
        sa.Column('access_token', sa.String(length=255), nullable=True, comment='Access token'),
        sa.Column('refresh_token', sa.String(length=255), nullable=True, comment='Refresh token'),
        sa.Column('token_expires_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Token expiration time'),
        sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional data'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.ForeignKeyConstraint(
            ['provider_id'],
            ['public.portal_third_party_provider.id'],
            name=op.f('fk_portal_user_third_party_auth_provider_id_portal_third_party_provider'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_user_third_party_auth_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_user_third_party_auth')),
        sa.UniqueConstraint('user_id', 'provider_id', name=op.f('uq_portal_user_third_party_auth_user_id_provider_id')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_user_third_party_auth_user_id'), 'portal_user_third_party_auth', ['user_id'], unique=False, schema='public')
    op.create_table(
        'portal_role_permission',
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('expire_date', sa.DateTime(), nullable=True, comment='Expiration time, can be used for temporary authorization'),
        sa.ForeignKeyConstraint(
            ['permission_id'],
            ['public.portal_permission.id'],
            name=op.f('fk_portal_role_permission_permission_id_portal_permission'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['role_id'], ['public.portal_role.id'], name=op.f('fk_portal_role_permission_role_id_portal_role'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('permission_id', 'role_id', name=op.f('pk_portal_role_permission')),
        schema='public'
    )
    op.create_index('ix_portal_role_permission_expire_date', 'portal_role_permission', ['expire_date'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_portal_role_permission_expire_date', table_name='portal_role_permission', schema='public')
    op.drop_table('portal_role_permission', schema='public')
    op.drop_index(op.f('ix_portal_user_third_party_auth_user_id'), table_name='portal_user_third_party_auth', schema='public')
    op.drop_table('portal_user_third_party_auth', schema='public')
    op.drop_table('portal_user_role', schema='public')
    op.drop_index(op.f('ix_portal_user_profile_user_id'), table_name='portal_user_profile', schema='public')
    op.drop_table('portal_user_profile', schema='public')
    op.drop_table('portal_permission', schema='public')
    op.drop_table('portal_verb', schema='public')
    op.drop_table('portal_user', schema='public')
    op.drop_table('portal_third_party_provider', schema='public')
    op.drop_table('portal_role', schema='public')
    op.drop_table('portal_resource', schema='public')
    # ### end Alembic commands ###
