"""
Alter id field in ModelBase to use gen_random_uuid() as server_default
--------------------------------------------------
Revision ID: d8ff6ad99ba8
Revises: f9061989ae90
Create Date: 2025-08-29 22:58:34.037605
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd8ff6ad99ba8'
down_revision: Union[str, None] = 'f9061989ae90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'demo', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_conference', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_event_schedule', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_faq', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_faq_category', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_fcm_device', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_feedback', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file_association', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file_rendition', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_instructor', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_language', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_location', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_log', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_notification', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_notification_history', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_permission', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_resource', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_role', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_testimony', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_third_party_provider', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_translation', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user_profile', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user_third_party_auth', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_verb', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_workshop', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_workshop_registration', 'id',
        existing_type=sa.UUID(),
        server_default=sa.text('gen_random_uuid()'),
        existing_comment='Primary Key',
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'portal_workshop_registration', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_workshop', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_verb', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user_third_party_auth', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user_profile', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_user', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_translation', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_third_party_provider', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_testimony', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_role', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_resource', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_permission', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_notification_history', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_notification', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_log', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_location', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_language', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_instructor', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file_rendition', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file_association', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_file', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_feedback', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_fcm_device', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_faq_category', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_faq', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_event_schedule', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'portal_conference', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    op.alter_column(
        'demo', 'id',
        existing_type=sa.UUID(),
        server_default=None,
        existing_comment='Primary Key',
        existing_nullable=False
    )
    # ### end Alembic commands ###
