"""
Add more fields for resource model
--------------------------------------------------
Revision ID: f9061989ae90
Revises: 52d8333a6ca5
Create Date: 2025-08-28 01:02:05.437302
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f9061989ae90'
down_revision: Union[str, None] = '52d8333a6ca5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_resource', sa.Column('pid', sa.UUID(), nullable=True, comment='Parent resource id'))
    op.add_column('portal_resource', sa.Column('key', sa.String(length=128), nullable=False, comment='Resource key and front-end corresponding'))
    op.add_column('portal_resource', sa.Column('icon', sa.String(length=32), nullable=True, comment='Resource icon'))
    op.add_column('portal_resource', sa.Column('path', sa.String(length=256), nullable=True, comment='Resource path'))
    op.add_column('portal_resource', sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='Is resource visible'))
    op.add_column(
        'portal_resource',
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        )
    )
    op.create_unique_constraint(op.f('uq_portal_resource_key'), 'portal_resource', ['key'], schema='public')
    op.create_foreign_key(
        op.f('fk_portal_resource_pid_portal_resource'),
        'portal_resource',
        'portal_resource',
        ['pid'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        ondelete='CASCADE'
    )
    op.drop_column('portal_resource', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_resource', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Is resource active'))
    op.drop_constraint(op.f('fk_portal_resource_pid_portal_resource'), 'portal_resource', schema='public', type_='foreignkey')
    op.drop_constraint(op.f('uq_portal_resource_key'), 'portal_resource', schema='public', type_='unique')
    op.drop_column('portal_resource', 'sequence')
    op.drop_column('portal_resource', 'is_visible')
    op.drop_column('portal_resource', 'path')
    op.drop_column('portal_resource', 'icon')
    op.drop_column('portal_resource', 'key')
    op.drop_column('portal_resource', 'pid')
    # ### end Alembic commands ###
