"""
Adjust fcm user device model
--------------------------------------------------
Revision ID: 52d8333a6ca5
Revises: 6cfe5842e229
Create Date: 2025-08-27 02:24:24.299272
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52d8333a6ca5'
down_revision: Union[str, None] = '6cfe5842e229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'portal_fcm_user_device', 'user_id',
        existing_type=sa.UUID(),
        comment=None,
        existing_comment='User ID',
        existing_nullable=False
    )
    op.alter_column(
        'portal_fcm_user_device', 'device_id',
        existing_type=sa.UUID(),
        comment=None,
        existing_comment='FCM Device ID',
        existing_nullable=False
    )
    # op.create_primary_key(op.f('pk_portal_fcm_user_device'), 'portal_fcm_user_device', ['user_id', 'device_id'], schema='public')
    op.create_unique_constraint(op.f('uq_portal_fcm_user_device_user_id_device_id'), 'portal_fcm_user_device', ['user_id', 'device_id'], schema='public')
    op.drop_column('portal_fcm_user_device', 'id')
    op.drop_column('portal_fcm_user_device', 'description')
    op.drop_column('portal_fcm_user_device', 'created_by_id')
    op.drop_column('portal_fcm_user_device', 'created_by')
    op.drop_column('portal_fcm_user_device', 'remark')
    op.drop_column('portal_fcm_user_device', 'updated_by_id')
    op.drop_column('portal_fcm_user_device', 'delete_reason')
    op.drop_column('portal_fcm_user_device', 'updated_at')
    op.drop_column('portal_fcm_user_device', 'created_at')
    op.drop_column('portal_fcm_user_device', 'is_deleted')
    op.drop_column('portal_fcm_user_device', 'updated_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_fcm_user_device', sa.Column('updated_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Update User Name'))
    op.add_column(
        'portal_fcm_user_device',
        sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Is Deleted(Logical Delete)')
    )
    op.add_column(
        'portal_fcm_user_device',
        sa.Column(
            'created_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
            comment='Create Date'
        )
    )
    op.add_column(
        'portal_fcm_user_device',
        sa.Column(
            'updated_at',
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            autoincrement=False,
            nullable=False,
            comment='Update Date'
        )
    )
    op.add_column('portal_fcm_user_device', sa.Column('delete_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Delete Reason'))
    op.add_column('portal_fcm_user_device', sa.Column('updated_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Update User ID'))
    op.add_column('portal_fcm_user_device', sa.Column('remark', sa.VARCHAR(length=256), autoincrement=False, nullable=True, comment='Remark'))
    op.add_column('portal_fcm_user_device', sa.Column('created_by', sa.VARCHAR(length=64), autoincrement=False, nullable=False, comment='Create User Name'))
    op.add_column('portal_fcm_user_device', sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True, comment='Create User ID'))
    op.add_column('portal_fcm_user_device', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True, comment='Description'))
    op.add_column('portal_fcm_user_device', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key'))
    op.drop_constraint(op.f('pk_portal_fcm_user_device'), 'portal_fcm_user_device', schema='public', type_='primary')
    op.drop_constraint(op.f('uq_portal_fcm_user_device_user_id_device_id'), 'portal_fcm_user_device', schema='public', type_='unique')
    op.alter_column(
        'portal_fcm_user_device', 'device_id',
        existing_type=sa.UUID(),
        comment='FCM Device ID',
        existing_nullable=False,
    )
    op.alter_column(
        'portal_fcm_user_device', 'user_id',
        existing_type=sa.UUID(),
        comment='User ID',
        existing_nullable=False
    )
    op.create_primary_key(op.f('pk_portal_fcm_user_device'), 'portal_fcm_user_device', ['id'], schema='public')
    # ### end Alembic commands ###
