"""
Remove unnecessary field in user profile
--------------------------------------------------
Revision ID: 5e0db16a3a0e
Revises: d8fa635e06eb
Create Date: 2025-09-28 07:44:06.981623
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '5e0db16a3a0e'
down_revision: Union[str, None] = 'd8fa635e06eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_user_profile', 'is_deleted')
    op.drop_column('portal_user_profile', 'delete_reason')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_user_profile', sa.Column('delete_reason', sa.VARCHAR(length=64), autoincrement=False, nullable=True, comment='Delete Reason'))
    op.add_column('portal_user_profile', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Is Deleted(Logical Delete)'))
    # ### end Alembic commands ###
