"""
Add sequence column to workshop
--------------------------------------------------
Revision ID: a11a9424df0e
Revises: b85513545130
Create Date: 2025-11-20 15:50:03.856792
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a11a9424df0e'
down_revision: Union[str, None] = 'b85513545130'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_workshop', sa.Column('sequence', sa.Float(), server_default=sa.text('extract(epoch from now())'), nullable=True, comment='Display sort, small to large, positive sort, default value current timestamp'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_workshop', 'sequence')
    # ### end Alembic commands ###
