"""
Create file-related and log tables
--------------------------------------------------
Revision ID: 504ce418befa
Revises: 4372a1805460
Create Date: 2025-08-25 19:54:04.072328
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '504ce418befa'
down_revision: Union[str, None] = '4372a1805460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portal_file',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('original_name', sa.String(length=255), nullable=False, comment='Original filename as uploaded'),
        sa.Column('key', sa.String(length=512), nullable=False, comment='Storage object key(path)'),
        sa.Column('storage', sa.String(length=16), nullable=False, comment='Storage backend, e.g., s3, gcs, local'),
        sa.Column('bucket', sa.String(length=128), nullable=False, comment='S3 bucket name'),
        sa.Column('region', sa.String(length=32), nullable=False, comment='S3 region'),
        sa.Column('content_type', sa.String(length=128), nullable=True, comment='MIME type'),
        sa.Column('extension', sa.String(length=16), nullable=True, comment='File extension'),
        sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='File size in bytes'),
        sa.Column('checksum_md5', sa.String(length=32), nullable=True, comment='MD5 checksum of the file'),
        sa.Column('checksum_sha256', sa.String(length=64), nullable=True, comment='SHA-256 checksum of the file'),
        sa.Column('width', sa.Integer(), nullable=True, comment='Image width in pixels'),
        sa.Column('height', sa.Integer(), nullable=True, comment='Image height in pixels'),
        sa.Column('duration_seconds', sa.Float(), nullable=True, comment='Media duration in seconds'),
        sa.Column('status', sa.Integer(), nullable=False, comment='File status, refer to FileStatus enum'),
        sa.Column('version', sa.Integer(), nullable=False, comment='File version number'),
        sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Whether the file is public'),
        sa.Column('source', sa.Integer(), nullable=True, comment='Upload source, refer to UploadSource enum'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_file')),
        sa.UniqueConstraint('bucket', 'key', name=op.f('uq_portal_file_bucket_key')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_file_key'), 'portal_file', ['key'], unique=False, schema='public')
    op.create_table(
        'portal_log',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('record_id', sa.UUID(), nullable=True, comment='Record ID in the audited table'),
        sa.Column('operation_type', sa.Integer(), nullable=False, comment='Operation type. refer to libs.consts.enums.OperationType'),
        sa.Column('operation_code', sa.String(length=64), nullable=True, comment='Operation code(default use table name)'),
        sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete old record data'),
        sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Complete new record data'),
        sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Only the fields that changed with old/new values'),
        sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
        sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent string'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_log')),
        schema='public'
    )
    op.create_table(
        'portal_file_association',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('file_id', sa.UUID(), nullable=False, comment='File ID'),
        sa.Column('resource_id', sa.UUID(), nullable=False, comment='Resource ID'),
        sa.Column('resource_name', sa.String(length=32), nullable=False, comment='Resource name(default table name)'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.ForeignKeyConstraint(['file_id'], ['public.portal_file.id'], name=op.f('fk_portal_file_association_file_id_portal_file'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_file_association')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_file_association_file_id'), 'portal_file_association', ['file_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_file_association_resource_id'), 'portal_file_association', ['resource_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_file_association_resource_name'), 'portal_file_association', ['resource_name'], unique=False, schema='public')
    op.create_table(
        'portal_file_rendition',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('original_file_id', sa.UUID(), nullable=False, comment='Original file ID'),
        sa.Column('rendition_type', sa.String(length=32), nullable=False, comment='Rendition type, e.g., max-100x100, original'),
        sa.Column('key', sa.String(length=512), nullable=False, comment='Storage object key(path) for this rendition'),
        sa.Column('storage', sa.String(length=16), nullable=False, comment='Storage backend for this rendition'),
        sa.Column('bucket', sa.String(length=128), nullable=False, comment='S3 bucket for this rendition'),
        sa.Column('region', sa.String(length=32), nullable=False, comment='S3 region for this rendition'),
        sa.Column('width', sa.Integer(), nullable=True, comment='Rendition width in pixels'),
        sa.Column('height', sa.Integer(), nullable=True, comment='Rendition height in pixels'),
        sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='Rendition file size in bytes'),
        sa.Column('checksum_md5', sa.String(length=32), nullable=True, comment='MD5 checksum of the rendition'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.ForeignKeyConstraint(
            ['original_file_id'],
            ['public.portal_file.id'],
            name=op.f('fk_portal_file_rendition_original_file_id_portal_file'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_file_rendition')),
        sa.UniqueConstraint('original_file_id', 'rendition_type', name=op.f('uq_portal_file_rendition_original_file_id_rendition_type')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_file_rendition_key'), 'portal_file_rendition', ['key'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_file_rendition_original_file_id'), 'portal_file_rendition', ['original_file_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_permission_resource_id'), 'portal_permission', ['resource_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_permission_verb_id'), 'portal_permission', ['verb_id'], unique=False, schema='public')
    op.create_unique_constraint(op.f('uq_portal_permission_code'), 'portal_permission', ['code'], schema='public')
    op.add_column('portal_role_permission', sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'))
    op.alter_column(
        'portal_role_permission', 'expire_date',
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment='Expiration time, can be used for temporary authorization',
        existing_nullable=True
    )
    op.create_index(op.f('ix_portal_role_permission_permission_id'), 'portal_role_permission', ['permission_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_role_permission_role_id'), 'portal_role_permission', ['role_id'], unique=False, schema='public')
    op.create_unique_constraint(
        op.f('uq_portal_role_permission_role_id_permission_id'),
        'portal_role_permission',
        ['role_id', 'permission_id'],
        schema='public'
    )
    op.alter_column(
        'portal_user', 'email',
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=255),
        existing_comment='Email, unique identifier',
        existing_nullable=True
    )
    op.add_column('portal_user_role', sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'))
    op.create_index(op.f('ix_portal_user_role_role_id'), 'portal_user_role', ['role_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_user_role_user_id'), 'portal_user_role', ['user_id'], unique=False, schema='public')
    op.add_column('portal_user_third_party_auth', sa.Column('provider_uid', sa.String(length=255), nullable=False, comment='Provider UID'))
    op.drop_constraint('uq_portal_user_third_party_auth_user_id_provider_id', 'portal_user_third_party_auth', type_='unique')
    op.create_index(op.f('ix_portal_user_third_party_auth_provider_id'), 'portal_user_third_party_auth', ['provider_id'], unique=False, schema='public')
    op.create_unique_constraint(
        op.f('uq_portal_user_third_party_auth_user_id_provider_id_provider_uid'),
        'portal_user_third_party_auth',
        ['user_id', 'provider_id', 'provider_uid'],
        schema='public'
    )
    op.drop_constraint('fk_portal_user_third_party_auth_user_id_portal_user', 'portal_user_third_party_auth', type_='foreignkey')
    op.drop_constraint('fk_portal_user_third_party_auth_provider_id_portal_thir_4df8', 'portal_user_third_party_auth', type_='foreignkey')
    op.create_foreign_key(
        'fk_user_third_party_auth_provider',
        'portal_user_third_party_auth',
        'portal_third_party_provider',
        ['provider_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_user_third_party_auth_user',
        'portal_user_third_party_auth',
        'portal_user',
        ['user_id'],
        ['id'],
        source_schema='public',
        referent_schema='public',
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_third_party_auth_user', 'portal_user_third_party_auth', schema='public', type_='foreignkey')
    op.drop_constraint('fk_user_third_party_auth_provider', 'portal_user_third_party_auth', schema='public', type_='foreignkey')
    op.create_foreign_key(
        'fk_portal_user_third_party_auth_provider_id_portal_thir_4df8',
        'portal_user_third_party_auth',
        'portal_third_party_provider',
        ['provider_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.create_foreign_key(
        'fk_portal_user_third_party_auth_user_id_portal_user',
        'portal_user_third_party_auth',
        'portal_user',
        ['user_id'],
        ['id'],
        ondelete='CASCADE'
    )
    op.drop_constraint(
        op.f('uq_portal_user_third_party_auth_user_id_provider_id_provider_uid'),
        'portal_user_third_party_auth',
        schema='public',
        type_='unique'
    )
    op.drop_index(op.f('ix_portal_user_third_party_auth_provider_id'), table_name='portal_user_third_party_auth', schema='public')
    op.create_unique_constraint('uq_portal_user_third_party_auth_user_id_provider_id', 'portal_user_third_party_auth', ['user_id', 'provider_id'])
    op.drop_column('portal_user_third_party_auth', 'provider_uid')
    op.drop_index(op.f('ix_portal_user_role_user_id'), table_name='portal_user_role', schema='public')
    op.drop_index(op.f('ix_portal_user_role_role_id'), table_name='portal_user_role', schema='public')
    op.drop_column('portal_user_role', 'id')
    op.alter_column(
        'portal_user', 'email',
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=64),
        existing_comment='Email, unique identifier',
        existing_nullable=True
    )
    op.drop_constraint(op.f('uq_portal_role_permission_role_id_permission_id'), 'portal_role_permission', schema='public', type_='unique')
    op.drop_index(op.f('ix_portal_role_permission_role_id'), table_name='portal_role_permission', schema='public')
    op.drop_index(op.f('ix_portal_role_permission_permission_id'), table_name='portal_role_permission', schema='public')
    op.alter_column(
        'portal_role_permission', 'expire_date',
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment='Expiration time, can be used for temporary authorization',
        existing_nullable=True
    )
    op.drop_column('portal_role_permission', 'id')
    op.drop_constraint(op.f('uq_portal_permission_code'), 'portal_permission', schema='public', type_='unique')
    op.drop_index(op.f('ix_portal_permission_verb_id'), table_name='portal_permission', schema='public')
    op.drop_index(op.f('ix_portal_permission_resource_id'), table_name='portal_permission', schema='public')
    op.drop_index(op.f('ix_portal_file_rendition_original_file_id'), table_name='portal_file_rendition', schema='public')
    op.drop_index(op.f('ix_portal_file_rendition_key'), table_name='portal_file_rendition', schema='public')
    op.drop_table('portal_file_rendition', schema='public')
    op.drop_index(op.f('ix_portal_file_association_resource_name'), table_name='portal_file_association', schema='public')
    op.drop_index(op.f('ix_portal_file_association_resource_id'), table_name='portal_file_association', schema='public')
    op.drop_index(op.f('ix_portal_file_association_file_id'), table_name='portal_file_association', schema='public')
    op.drop_table('portal_file_association', schema='public')
    op.drop_table('portal_log', schema='public')
    op.drop_index(op.f('ix_portal_file_key'), table_name='portal_file', schema='public')
    op.drop_table('portal_file', schema='public')
    # ### end Alembic commands ###
