"""
Create models for all apps from existing structures
--------------------------------------------------
Revision ID: aaac852cf68d
Revises: 504ce418befa
Create Date: 2025-08-26 19:46:36.267282
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aaac852cf68d'
down_revision: Union[str, None] = '504ce418befa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portal_faq_category',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='Category name'),
        sa.Column('description', sa.Text(), nullable=True, comment='Category description'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_faq_category')),
        schema='public'
    )
    op.create_table(
        'portal_fcm_device',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('device_key', sa.String(length=255), nullable=False, comment='Device Key'),
        sa.Column('token', sa.String(length=255), nullable=False, comment='FCM token'),
        sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True, comment='Expiration time'),
        sa.Column('additional_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional device data'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_fcm_device')),
        sa.UniqueConstraint('device_key', name=op.f('uq_portal_fcm_device_device_key')),
        schema='public'
    )
    op.create_table(
        'portal_feedback',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='Feedback name'),
        sa.Column('email', sa.String(length=255), nullable=True, comment='Feedback email'),
        sa.Column('message', sa.Text(), nullable=False, comment='Feedback message'),
        sa.Column('status', sa.Integer(), nullable=True, comment='Feedback status'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_feedback')),
        schema='public'
    )
    op.create_table(
        'portal_instructor',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='Instructor name'),
        sa.Column('title', sa.String(length=255), nullable=True, comment='Instructor title'),
        sa.Column('bio', sa.Text(), nullable=True, comment='Instructor biography'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_instructor')),
        schema='public'
    )
    op.create_table(
        'portal_language',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('code', sa.String(length=10), nullable=False, comment='Language code'),
        sa.Column('name', sa.String(length=50), nullable=False, comment='Language name'),
        sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is language active'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_language')),
        sa.UniqueConstraint('code', name=op.f('uq_portal_language_code')),
        schema='public'
    )
    op.create_table(
        'portal_location',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='Location name'),
        sa.Column('address', sa.Text(), nullable=True, comment='Location address'),
        sa.Column('floor', sa.String(length=10), nullable=True, comment='Floor number'),
        sa.Column('room_number', sa.String(length=10), nullable=True, comment='Room number'),
        sa.Column('latitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='Latitude coordinate'),
        sa.Column('longitude', sa.DECIMAL(precision=9, scale=6), nullable=True, comment='Longitude coordinate'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_location')),
        schema='public'
    )
    op.create_table(
        'portal_notification',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='Notification title'),
        sa.Column('message', sa.Text(), nullable=False, comment='Notification message'),
        sa.Column('url', sa.String(length=500), nullable=True, comment='Notification URL'),
        sa.Column('type', sa.Integer(), nullable=False, comment='Notification type'),
        sa.Column('status', sa.Integer(), nullable=True, comment='Notification status'),
        sa.Column('failure_count', sa.Integer(), nullable=True, comment='Failure count'),
        sa.Column('success_count', sa.Integer(), nullable=True, comment='Success count'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_notification')),
        schema='public'
    )
    op.create_table(
        'portal_testimony',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('name', sa.String(length=255), nullable=False, comment='Testimony name'),
        sa.Column('phone_number', sa.String(length=16), nullable=True, comment='Phone number'),
        sa.Column('share', sa.Boolean(), nullable=True, comment='Share permission'),
        sa.Column('message', sa.Text(), nullable=False, comment='Testimony message'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_testimony')),
        schema='public'
    )
    op.create_table(
        'portal_conference',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='Conference title'),
        sa.Column('description', sa.Text(), nullable=True, comment='Conference description'),
        sa.Column('start_date', sa.Date(), nullable=False, comment='Conference start date'),
        sa.Column('end_date', sa.Date(), nullable=False, comment='Conference end date'),
        sa.Column('active', sa.Boolean(), nullable=True, comment='Is conference active'),
        sa.Column('location_id', sa.UUID(), nullable=True, comment='Location ID'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['location_id'],
            ['public.portal_location.id'],
            name=op.f('fk_portal_conference_location_id_portal_location'),
            ondelete='SET NULL'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_conference')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_conference_location_id'), 'portal_conference', ['location_id'], unique=False, schema='public')
    op.create_table(
        'portal_faq',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('category_id', sa.UUID(), nullable=False, comment='Category ID'),
        sa.Column('question', sa.Text(), nullable=False, comment='FAQ question'),
        sa.Column('answer', sa.Text(), nullable=False, comment='FAQ answer'),
        sa.Column('related_link', sa.String(length=500), nullable=True, comment='Related link URL'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['public.portal_faq_category.id'],
            name=op.f('fk_portal_faq_category_id_portal_faq_category'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_faq')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_faq_category_id'), 'portal_faq', ['category_id'], unique=False, schema='public')
    op.create_table(
        'portal_fcm_user_device',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('device_id', sa.UUID(), nullable=False, comment='FCM Device ID'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['device_id'],
            ['public.portal_fcm_device.id'],
            name=op.f('fk_portal_fcm_user_device_device_id_portal_fcm_device'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_fcm_user_device_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_fcm_user_device')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_fcm_user_device_device_id'), 'portal_fcm_user_device', ['device_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_fcm_user_device_user_id'), 'portal_fcm_user_device', ['user_id'], unique=False, schema='public')
    op.create_table(
        'portal_notification_history',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('notification_id', sa.UUID(), nullable=False, comment='Notification ID'),
        sa.Column('device_id', sa.UUID(), nullable=False, comment='Device ID'),
        sa.Column('message_id', sa.String(length=255), nullable=True, comment='FCM message ID'),
        sa.Column('exception', sa.Text(), nullable=True, comment='Exception message'),
        sa.Column('status', sa.Integer(), nullable=False, comment='History status'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['device_id'],
            ['public.portal_fcm_device.id'],
            name=op.f('fk_portal_notification_history_device_id_portal_fcm_device'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['notification_id'],
            ['public.portal_notification.id'],
            name=op.f('fk_portal_notification_history_notification_id_portal_notification'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_notification_history')),
        sa.UniqueConstraint('notification_id', 'device_id', name=op.f('uq_portal_notification_history_notification_id_device_id')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_notification_history_device_id'), 'portal_notification_history', ['device_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_notification_history_notification_id'), 'portal_notification_history', ['notification_id'], unique=False, schema='public')
    op.create_table(
        'portal_translation',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('language_id', sa.UUID(), nullable=False, comment='Language ID'),
        sa.Column('content_type', sa.String(length=50), nullable=False, comment='Content type'),
        sa.Column('object_id', sa.UUID(), nullable=False, comment='Object ID'),
        sa.Column('field_name', sa.String(length=50), nullable=False, comment='Field name'),
        sa.Column('translated_text', sa.Text(), nullable=False, comment='Translated text'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['language_id'],
            ['public.portal_language.id'],
            name=op.f('fk_portal_translation_language_id_portal_language'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_translation')),
        sa.UniqueConstraint(
            'content_type',
            'object_id',
            'language_id',
            'field_name',
            name=op.f('uq_portal_translation_content_type_object_id_language_id_field_name')
        ),
        schema='public'
    )
    op.create_index(op.f('ix_portal_translation_language_id'), 'portal_translation', ['language_id'], unique=False, schema='public')
    op.create_table(
        'portal_conference_instructors',
        sa.Column('conference_id', sa.UUID(), nullable=False),
        sa.Column('instructor_id', sa.UUID(), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=True, comment='Is primary instructor'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.ForeignKeyConstraint(
            ['conference_id'],
            ['public.portal_conference.id'],
            name=op.f('fk_portal_conference_instructors_conference_id_portal_conference'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['instructor_id'],
            ['public.portal_instructor.id'],
            name=op.f('fk_portal_conference_instructors_instructor_id_portal_instructor'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('conference_id', 'instructor_id', name=op.f('pk_portal_conference_instructors')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_conference_instructors_conference_id'), 'portal_conference_instructors', ['conference_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_conference_instructors_instructor_id'), 'portal_conference_instructors', ['instructor_id'], unique=False, schema='public')
    op.create_table(
        'portal_event_schedule',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('conference_id', sa.UUID(), nullable=False, comment='Conference ID'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='Event title'),
        sa.Column('description', sa.Text(), nullable=True, comment='Event description'),
        sa.Column('start_datetime', sa.TIMESTAMP(timezone=True), nullable=False, comment='Start DateTime'),
        sa.Column('end_datetime', sa.TIMESTAMP(timezone=True), nullable=False, comment='End DateTime'),
        sa.Column('text_color', sa.String(length=7), nullable=True, comment='Text color in hex format'),
        sa.Column('background_color', sa.String(length=7), nullable=True, comment='Background color in hex format'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.ForeignKeyConstraint(
            ['conference_id'],
            ['public.portal_conference.id'],
            name=op.f('fk_portal_event_schedule_conference_id_portal_conference'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_event_schedule')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_event_schedule_conference_id'), 'portal_event_schedule', ['conference_id'], unique=False, schema='public')
    op.create_table(
        'portal_workshop',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('title', sa.String(length=255), nullable=False, comment='Workshop title'),
        sa.Column('start_datetime', sa.TIMESTAMP(timezone=True), nullable=False, comment='Start datetime'),
        sa.Column('end_datetime', sa.TIMESTAMP(timezone=True), nullable=False, comment='End datetime'),
        sa.Column('conference_id', sa.UUID(), nullable=False, comment='Conference ID'),
        sa.Column('location_id', sa.UUID(), nullable=True, comment='Location ID'),
        sa.Column('participants_limit', sa.BigInteger(), nullable=True, comment='Participants limit'),
        sa.Column('slido_url', sa.String(length=500), nullable=True, comment='Slido URL'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(
            ['conference_id'],
            ['public.portal_conference.id'],
            name=op.f('fk_portal_workshop_conference_id_portal_conference'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['location_id'],
            ['public.portal_location.id'],
            name=op.f('fk_portal_workshop_location_id_portal_location'),
            ondelete='RESTRICT'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_workshop')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_workshop_conference_id'), 'portal_workshop', ['conference_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_workshop_location_id'), 'portal_workshop', ['location_id'], unique=False, schema='public')
    op.create_table(
        'portal_workshop_instructor',
        sa.Column('workshop_id', sa.UUID(), nullable=False),
        sa.Column('instructor_id', sa.UUID(), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=True, comment='Is primary instructor'),
        sa.Column(
            'sequence',
            sa.Float(),
            server_default=sa.text('extract(epoch from now())'),
            nullable=True,
            comment='Display sort, small to large, positive sort, default value current timestamp'
        ),
        sa.ForeignKeyConstraint(
            ['instructor_id'],
            ['public.portal_instructor.id'],
            name=op.f('fk_portal_workshop_instructor_instructor_id_portal_instructor'),
            ondelete='CASCADE'
        ),
        sa.ForeignKeyConstraint(
            ['workshop_id'],
            ['public.portal_workshop.id'],
            name=op.f('fk_portal_workshop_instructor_workshop_id_portal_workshop'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('workshop_id', 'instructor_id', name=op.f('pk_portal_workshop_instructor')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_workshop_instructor_instructor_id'), 'portal_workshop_instructor', ['instructor_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_workshop_instructor_workshop_id'), 'portal_workshop_instructor', ['workshop_id'], unique=False, schema='public')
    op.create_table(
        'portal_workshop_registration',
        sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key'),
        sa.Column('workshop_id', sa.UUID(), nullable=False, comment='Workshop ID'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('registered_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True, comment='Registration time'),
        sa.Column('unregistered_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Unregistration time'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.Column('description', sa.Text(), nullable=True, comment='Description'),
        sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_workshop_registration_user_id_portal_user'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(
            ['workshop_id'],
            ['public.portal_workshop.id'],
            name=op.f('fk_portal_workshop_registration_workshop_id_portal_workshop'),
            ondelete='CASCADE'
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_workshop_registration')),
        sa.UniqueConstraint('workshop_id', 'user_id', name=op.f('uq_portal_workshop_registration_workshop_id_user_id')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_workshop_registration_user_id'), 'portal_workshop_registration', ['user_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_workshop_registration_workshop_id'), 'portal_workshop_registration', ['workshop_id'], unique=False, schema='public')
    op.drop_column('portal_permission', 'expire_date')
    op.drop_column('portal_role_permission', 'id')
    op.create_index(op.f('ix_portal_user_is_active'), 'portal_user', ['is_active'], unique=False, schema='public')
    op.drop_column('portal_user_role', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_user_role', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key'))
    op.drop_index(op.f('ix_portal_user_is_active'), table_name='portal_user', schema='public')
    op.add_column('portal_role_permission', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key'))
    op.add_column(
        'portal_permission',
        sa.Column(
            'expire_date',
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
            comment='Expiration time, can be used for temporary authorization'
        )
    )
    op.drop_index(op.f('ix_portal_workshop_registration_workshop_id'), table_name='portal_workshop_registration', schema='public')
    op.drop_index(op.f('ix_portal_workshop_registration_user_id'), table_name='portal_workshop_registration', schema='public')
    op.drop_table('portal_workshop_registration', schema='public')
    op.drop_index(op.f('ix_portal_workshop_instructor_workshop_id'), table_name='portal_workshop_instructor', schema='public')
    op.drop_index(op.f('ix_portal_workshop_instructor_instructor_id'), table_name='portal_workshop_instructor', schema='public')
    op.drop_table('portal_workshop_instructor', schema='public')
    op.drop_index(op.f('ix_portal_workshop_location_id'), table_name='portal_workshop', schema='public')
    op.drop_index(op.f('ix_portal_workshop_conference_id'), table_name='portal_workshop', schema='public')
    op.drop_table('portal_workshop', schema='public')
    op.drop_index(op.f('ix_portal_event_schedule_conference_id'), table_name='portal_event_schedule', schema='public')
    op.drop_table('portal_event_schedule', schema='public')
    op.drop_index(op.f('ix_portal_conference_instructors_instructor_id'), table_name='portal_conference_instructors', schema='public')
    op.drop_index(op.f('ix_portal_conference_instructors_conference_id'), table_name='portal_conference_instructors', schema='public')
    op.drop_table('portal_conference_instructors', schema='public')
    op.drop_index(op.f('ix_portal_translation_language_id'), table_name='portal_translation', schema='public')
    op.drop_table('portal_translation', schema='public')
    op.drop_index(op.f('ix_portal_notification_history_notification_id'), table_name='portal_notification_history', schema='public')
    op.drop_index(op.f('ix_portal_notification_history_device_id'), table_name='portal_notification_history', schema='public')
    op.drop_table('portal_notification_history', schema='public')
    op.drop_index(op.f('ix_portal_fcm_user_device_user_id'), table_name='portal_fcm_user_device', schema='public')
    op.drop_index(op.f('ix_portal_fcm_user_device_device_id'), table_name='portal_fcm_user_device', schema='public')
    op.drop_table('portal_fcm_user_device', schema='public')
    op.drop_index(op.f('ix_portal_faq_category_id'), table_name='portal_faq', schema='public')
    op.drop_table('portal_faq', schema='public')
    op.drop_index(op.f('ix_portal_conference_location_id'), table_name='portal_conference', schema='public')
    op.drop_table('portal_conference', schema='public')
    op.drop_table('portal_testimony', schema='public')
    op.drop_table('portal_notification', schema='public')
    op.drop_table('portal_location', schema='public')
    op.drop_table('portal_language', schema='public')
    op.drop_table('portal_instructor', schema='public')
    op.drop_table('portal_feedback', schema='public')
    op.drop_table('portal_fcm_device', schema='public')
    op.drop_table('portal_faq_category', schema='public')
    # ### end Alembic commands ###
