"""
Add timezone field for conference, event sechedule and workshop models
--------------------------------------------------
Revision ID: 6cfe5842e229
Revises: aa0e78da02e6
Create Date: 2025-08-27 01:12:41.952825
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6cfe5842e229'
down_revision: Union[str, None] = 'aa0e78da02e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_conference', sa.Column('timezone', sa.String(length=255), nullable=False, comment='Timezone'))
    op.add_column('portal_event_schedule', sa.Column('timezone', sa.String(length=255), nullable=False, comment='Timezone'))
    op.add_column('portal_workshop', sa.Column('timezone', sa.String(length=255), nullable=False, comment='Timezone'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_workshop', 'timezone')
    op.drop_column('portal_event_schedule', 'timezone')
    op.drop_column('portal_conference', 'timezone')
    # ### end Alembic commands ###
