"""
Create auth releated models
--------------------------------------------------
Revision ID: 80234a5bc35f
Revises: d8ff6ad99ba8
Create Date: 2025-09-01 21:34:19.481290
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '80234a5bc35f'
down_revision: Union[str, None] = 'd8ff6ad99ba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'portal_auth_device',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='First seen at'),
        sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Last seen at'),
        sa.Column('last_ip', sa.String(length=45), nullable=True, comment='Last IP'),
        sa.Column('last_user_agent', sa.String(length=512), nullable=True, comment='Last user agent'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_auth_device_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_auth_device')),
        sa.UniqueConstraint('id', 'user_id', name=op.f('uq_portal_auth_device_id_user_id')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_auth_device_user_id'), 'portal_auth_device', ['user_id'], unique=False, schema='public')
    op.create_table(
        'portal_refresh_token',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
        sa.Column('user_id', sa.UUID(), nullable=False, comment='User ID'),
        sa.Column('device_id', sa.UUID(), nullable=True, comment='Device ID'),
        sa.Column('family_id', sa.UUID(), nullable=False, comment='Family ID'),
        sa.Column('parent_id', sa.UUID(), nullable=True, comment='Parent ID'),
        sa.Column('replaced_by_id', sa.UUID(), nullable=True, comment='Replaced by ID'),
        sa.Column('token_hash', sa.String(length=128), nullable=False, comment='Token hash'),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Expires at'),
        sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='Last used at'),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Revoked at'),
        sa.Column('revoked_reason', sa.String(length=32), nullable=True, comment='Revoked reason'),
        sa.Column('ip', sa.String(length=45), nullable=True, comment='IP'),
        sa.Column('user_agent', sa.String(length=512), nullable=True, comment='User agent'),
        sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
        sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
        sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
        sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
        sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
        sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
        sa.ForeignKeyConstraint(
            ['device_id'],
            ['public.portal_auth_device.id'],
            name=op.f('fk_portal_refresh_token_device_id_portal_auth_device'),
            ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['parent_id'],
            ['public.portal_refresh_token.id'],
            name=op.f('fk_portal_refresh_token_parent_id_portal_refresh_token'),
            ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['replaced_by_id'],
            ['public.portal_refresh_token.id'],
            name=op.f('fk_portal_refresh_token_replaced_by_id_portal_refresh_token'),
            ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_refresh_token_user_id_portal_user'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_refresh_token')),
        schema='public'
    )
    op.create_index(op.f('ix_portal_refresh_token_device_id'), 'portal_refresh_token', ['device_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_expires_at'), 'portal_refresh_token', ['expires_at'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_family_id'), 'portal_refresh_token', ['family_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_last_used_at'), 'portal_refresh_token', ['last_used_at'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_parent_id'), 'portal_refresh_token', ['parent_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_replaced_by_id'), 'portal_refresh_token', ['replaced_by_id'], unique=False, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_token_hash'), 'portal_refresh_token', ['token_hash'], unique=True, schema='public')
    op.create_index(op.f('ix_portal_refresh_token_user_id'), 'portal_refresh_token', ['user_id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portal_refresh_token_user_id'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_token_hash'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_replaced_by_id'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_parent_id'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_last_used_at'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_family_id'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_expires_at'), table_name='portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_refresh_token_device_id'), table_name='portal_refresh_token', schema='public')
    op.drop_table('portal_refresh_token', schema='public')
    op.drop_index(op.f('ix_portal_auth_device_user_id'), table_name='portal_auth_device', schema='public')
    op.drop_table('portal_auth_device', schema='public')
    # ### end Alembic commands ###
