"""
Adjust duplicate fields in models
--------------------------------------------------
Revision ID: 35a4821cae9c
Revises: aaac852cf68d
Create Date: 2025-08-26 20:16:57.290409
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '35a4821cae9c'
down_revision: Union[str, None] = 'aaac852cf68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_conference', sa.Column('is_active', sa.Boolean(), nullable=True, comment='Is conference active'))
    op.alter_column('portal_conference', 'description',
               existing_type=sa.TEXT(),
               comment='Description',
               existing_comment='Conference description',
               existing_nullable=True)
    op.drop_column('portal_conference', 'active')
    op.drop_constraint('fk_portal_conference_instructors_instructor_id_portal_i_b7a4', 'portal_conference_instructors', type_='foreignkey')
    op.drop_constraint('fk_portal_conference_instructors_conference_id_portal_c_6e2d', 'portal_conference_instructors', type_='foreignkey')
    op.create_foreign_key('fk_conference_instructors_conference_id', 'portal_conference_instructors', 'portal_conference', ['conference_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.create_foreign_key('fk_conference_instructors_instructor_id', 'portal_conference_instructors', 'portal_instructor', ['instructor_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    op.alter_column('portal_event_schedule', 'description',
               existing_type=sa.TEXT(),
               comment='Description',
               existing_comment='Event description',
               existing_nullable=True)
    op.alter_column('portal_faq_category', 'description',
               existing_type=sa.TEXT(),
               comment='Description',
               existing_comment='Category description',
               existing_nullable=True)
    op.drop_constraint('fk_portal_notification_history_notification_id_portal_n_9b72', 'portal_notification_history', type_='foreignkey')
    op.create_foreign_key('fk_notification_history_notification_id', 'portal_notification_history', 'portal_notification', ['notification_id'], ['id'], source_schema='public', referent_schema='public', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notification_history_notification_id', 'portal_notification_history', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_portal_notification_history_notification_id_portal_n_9b72', 'portal_notification_history', 'portal_notification', ['notification_id'], ['id'], ondelete='CASCADE')
    op.alter_column('portal_faq_category', 'description',
               existing_type=sa.TEXT(),
               comment='Category description',
               existing_comment='Description',
               existing_nullable=True)
    op.alter_column('portal_event_schedule', 'description',
               existing_type=sa.TEXT(),
               comment='Event description',
               existing_comment='Description',
               existing_nullable=True)
    op.drop_constraint('fk_conference_instructors_instructor_id', 'portal_conference_instructors', schema='public', type_='foreignkey')
    op.drop_constraint('fk_conference_instructors_conference_id', 'portal_conference_instructors', schema='public', type_='foreignkey')
    op.create_foreign_key('fk_portal_conference_instructors_conference_id_portal_c_6e2d', 'portal_conference_instructors', 'portal_conference', ['conference_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_portal_conference_instructors_instructor_id_portal_i_b7a4', 'portal_conference_instructors', 'portal_instructor', ['instructor_id'], ['id'], ondelete='CASCADE')
    op.add_column('portal_conference', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True, comment='Is conference active'))
    op.alter_column('portal_conference', 'description',
               existing_type=sa.TEXT(),
               comment='Conference description',
               existing_comment='Description',
               existing_nullable=True)
    op.drop_column('portal_conference', 'is_active')
    # ### end Alembic commands ###
