"""
Adjusted notification related models
--------------------------------------------------
Revision ID: 0a2b8098e586
Revises: a11a9424df0e
Create Date: 2026-02-07 18:29:02.013852
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0a2b8098e586"
down_revision: Union[str, None] = "a11a9424df0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("portal_notification", sa.Column("method", sa.Integer(), nullable=False, comment="Notification method. Ref: NotificationMethod enum"))
    op.alter_column(
        "portal_notification", "type",
        existing_type=sa.INTEGER(),
        comment="Notification type. Ref: NotificationType enum",
        existing_comment="Notification type",
        existing_nullable=False
    )
    op.add_column("portal_notification_history", sa.Column("is_read", sa.Boolean(), server_default=sa.text("false"), nullable=False, comment="Is read"))
    op.alter_column(
        "portal_notification_history", "status",
        existing_type=sa.INTEGER(),
        comment="History status. Ref: NotificationHistoryStatus enum",
        existing_comment="History status",
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "portal_notification_history", "status",
        existing_type=sa.INTEGER(),
        comment="History status",
        existing_comment="History status. Ref: NotificationStatus enum",
        existing_nullable=False
    )
    op.drop_column("portal_notification_history", "is_read")
    op.alter_column(
        "portal_notification", "type",
        existing_type=sa.INTEGER(),
        comment="Notification type",
        existing_comment="Notification type. Ref: NotificationType enum",
        existing_nullable=False
    )
    op.drop_column("portal_notification", "method")
    # ### end Alembic commands ###
