"""
Add code field to TicketType table
--------------------------------------------------
Revision ID: 0eb014c0d533
Revises: c122b9632a7f
Create Date: 2026-03-04 08:20:22.520139
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0eb014c0d533'
down_revision: Union[str, None] = 'c122b9632a7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_ticket_type', sa.Column('code', sa.String(length=32), nullable=True, comment='Ticket type code'))
    op.create_unique_constraint(op.f('uq_portal_ticket_type_code'), 'portal_ticket_type', ['code'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_portal_ticket_type_code'), 'portal_ticket_type', schema='public', type_='unique')
    op.drop_column('portal_ticket_type', 'code')
    # ### end Alembic commands ###
