"""
Add ticket releated tables
--------------------------------------------------
Revision ID: 0bf715cfcecf
Revises: 0a2b8098e586
Create Date: 2026-02-15 16:22:30.918213
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0bf715cfcecf'
down_revision: Union[str, None] = '0a2b8098e586'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_ticket_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Ticket type name'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_ticket_type')),
    sa.UniqueConstraint('name', name=op.f('uq_portal_ticket_type_name')),
    schema='public'
    )
    op.create_table('portal_user_ticket',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='Primary Key'),
    sa.Column('ticket_type_id', sa.UUID(), nullable=False, comment='Ticket type id'),
    sa.Column('order_id', sa.UUID(), nullable=False, comment='Order id'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User id'),
    sa.Column('is_checked_in', sa.Boolean(), nullable=True, comment='Is checked in'),
    sa.Column('checked_in_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='Checked in at'),
    sa.Column('identity', sa.String(length=32), nullable=True, comment='Identity'),
    sa.Column('belong_church', sa.String(length=64), nullable=True, comment='Belong church'),
    sa.Column('created_by_id', sa.UUID(), nullable=True, comment='Create User ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Create Date'),
    sa.Column('created_by', sa.String(length=64), nullable=False, comment='Create User Name'),
    sa.Column('updated_by_id', sa.UUID(), nullable=True, comment='Update User ID'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Update Date'),
    sa.Column('updated_by', sa.String(length=64), nullable=False, comment='Update User Name'),
    sa.Column('delete_reason', sa.String(length=64), nullable=True, comment='Delete Reason'),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False, comment='Is Deleted(Logical Delete)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Description'),
    sa.Column('remark', sa.String(length=256), nullable=True, comment='Remark'),
    sa.ForeignKeyConstraint(['ticket_type_id'], ['public.portal_ticket_type.id'], name=op.f('fk_portal_user_ticket_ticket_type_id_portal_ticket_type'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['public.portal_user.id'], name=op.f('fk_portal_user_ticket_user_id_portal_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portal_user_ticket')),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portal_user_ticket', schema='public')
    op.drop_table('portal_ticket_type', schema='public')
    # ### end Alembic commands ###
