"""
Add ticket image url field
--------------------------------------------------
Revision ID: d68f0c5ed6b0
Revises: 566ba655f276
Create Date: 2026-03-20 12:25:26.877570
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd68f0c5ed6b0'
down_revision: Union[str, None] = '566ba655f276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_ticket_type', sa.Column('image_url', sa.Text(), nullable=True, comment='Ticket image url'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_ticket_type', 'image_url')
    # ### end Alembic commands ###
