"""

--------------------------------------------------
Revision ID: ffc1db6c8f48
Revises: 118fcb1bf4dd
Create Date: 2026-04-13 02:03:23.477695
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ffc1db6c8f48'
down_revision: Union[str, None] = '118fcb1bf4dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portal_log', 'operation_type',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               comment='Operation type string (OperationType.value). refer to libs.consts.enums.OperationType',
               existing_comment='Operation type. refer to libs.consts.enums.OperationType',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portal_log', 'operation_type',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               comment='Operation type. refer to libs.consts.enums.OperationType',
               existing_comment='Operation type string (OperationType.value). refer to libs.consts.enums.OperationType',
               existing_nullable=False)
    # ### end Alembic commands ###
