"""
Add is_creative and is_leadership columns to portal_workshop
--------------------------------------------------
Revision ID: 78ae1aaa282f
Revises: 0eb014c0d533
Create Date: 2026-03-17 20:08:49.246830
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '78ae1aaa282f'
down_revision: Union[str, None] = '0eb014c0d533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_workshop', sa.Column('is_creative', sa.Boolean(), nullable=True, comment='Is creative workshop', server_default=sa.text('false')))
    op.add_column('portal_workshop', sa.Column('is_leadership', sa.Boolean(), nullable=True, comment='Is leadership workshop', server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_workshop', 'is_leadership')
    op.drop_column('portal_workshop', 'is_creative')
    # ### end Alembic commands ###
