"""
Alter unique constraint on portal_ticket_type.code
--------------------------------------------------
Revision ID: 118fcb1bf4dd
Revises: d68f0c5ed6b0
Create Date: 2026-03-31 11:21:09.695014
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '118fcb1bf4dd'
down_revision: Union[str, None] = 'd68f0c5ed6b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_portal_ticket_type_code'), 'portal_ticket_type', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_portal_ticket_type_code'), 'portal_ticket_type', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
