"""
Add is_redeemed column to portal_user_ticket
--------------------------------------------------
Revision ID: c122b9632a7f
Revises: 0bf715cfcecf
Create Date: 2026-02-16 17:19:54.571185
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c122b9632a7f'
down_revision: Union[str, None] = '0bf715cfcecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portal_user_ticket', sa.Column('is_redeemed', sa.Boolean(), nullable=True, comment='Is redeemed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portal_user_ticket', 'is_redeemed')
    # ### end Alembic commands ###
