"""
Alter portal_user table to make email non-nullable and phone_number nullable.
--------------------------------------------------
Revision ID: 566ba655f276
Revises: 78ae1aaa282f
Create Date: 2026-03-20 11:08:41.524653
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '566ba655f276'
down_revision: Union[str, None] = '78ae1aaa282f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portal_user', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_comment='Phone number, unique identifier')
    op.alter_column('portal_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_comment='Email, unique identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portal_user', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_comment='Email, unique identifier')
    op.alter_column('portal_user', 'phone_number',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_comment='Phone number, unique identifier')
    # ### end Alembic commands ###
